### ISSUE TITLE
Documentation:  data source in R/data.R

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiralvaccine#218] opened 2023-07-04 14:32 UTC
### Let us know where something needs a refresh or put your idea here!

Hi admiralvaccine team, could data source be added to [data.R](https://github.com/pharmaverse/admiralvaccine/blob/main/R/data.R)? e.g., [data.R from admiralophtha](https://github.com/pharmaverse/admiralophtha/blob/main/R/data.R), [data.R from admiral.test](https://github.com/pharmaverse/admiral.test/blob/main/R/data.R)
Thanks! Link https://github.com/pharmaverse/admiraldata/issues/4

**Comment by ahasoplakus** [comment] 2023-07-25 11:12
Thanks @kaz462, the data sources have been added to **R/data.R**. Closing this issue.

**Comment by kaz462** [comment] 2023-07-25 14:43
Thanks @ahasoplakus ! 
For the data sources, could you please list the original sources/programs instead of the URLs in `admiralvaccine`, e.g., some data are copies from `admiral.test`, some are reconstructed in programs like the following one from `admiralophtha`. 
(This information is needed for `pharmaversesdtm`, so that we can recreate the `admiralvaccine` data there. Thanks again for working on this!)

```r
#' Best Corrected Visual Acuity Analysis Dataset
#'
#' An example Best Corrected Visual Acuity (BCVA) analysis dataset
#' @keywords datasets
#' @family datasets
#' @source
#' Derived from the `oe` and `ADSL` datasets using `{admiral}`, `{admiralophtha}` and
#' (\url{https://github.com/pharmaverse/admiralophtha/blob/main/inst/templates/ad_adbcva.R})
#'
"admiralophtha_adbcva"
```

**Comment by ahasoplakus** [comment] 2023-07-27 17:03
@kaz462 Thank you for the clarification. @arjoon-r @vikrams95 could you please check on your end?

**Comment by vikrams95** [comment] 2023-07-28 06:38
@kaz462 Thanks for bringing up this, we do not have source code for the datasets which we have used except `vx_is` and `vx_suppis`. We just mocked the data and used it due to data complexity and time constraint, anyway we will work on adding source code for all the datasets and deploy it on future release. Thanks!!

**Comment by kaz462** [comment] 2023-07-28 18:26
@vikrams95 @ahasoplakus Thanks for checking!
cc: @pharmaverse/admiraldata

**Comment by manciniedoardo** [comment] 2023-08-08 14:00
> We just mocked the data and used it due to data complexity and time constraint

Hi @vikrams95 @ahasoplakus @neetusan.

In any pharmaverse package, **transparency** and **reproducibility** are key - we need to be able to see where data/code comes from, and what we are doing to it. This also ensures that nothing proprietary is accidentally open-sourced. Thus, we cannot just mock up the data, and not include the source program for it or documentation explaining its source. I should also add that the absence of source programs also makes editing your data in the future much harder.

As such, please could you make it a priority to locate your source programs so that we can include them in pharmaversesdtm, or alternatively re-create the source programs entirely. Otherwise we will not be able to include these datasets in pharmaversesdtm. 

Thanks!

**Comment by arjoon-r** [comment] 2023-08-31 05:55
Hi @kaz462 and @manciniedoardo, The Data sources has been included in **R/data.R** and alsowe have created the source program for each Vaccine specific - SDTM datasets and added them in **inst/create_vx_data** folder.

**Comment by manciniedoardo** [comment] 2023-08-31 07:44
Thanks @arjoon-r! The plan now would be to move the programs over to `{pharmaversesdtm}` (our one source for test SDTM data). However we probably will not have time to include this in the first release of `{pharmaversesdtm}` because that is scheduled for 4th Sept. Additionally, although in our [guidance for test data](https://pharmaverse.github.io/pharmaversesdtm/devel/#adding-new-sdtm-datasets) I am seeing that it's not listed as mandatory to use the CDISC pilot `DM` dataset as a basis (so as to have consistent USUBJIDs etc) all the other test data does do this so it might be worth implementing this in the vaccine programs as well.

**Closed** 2023-10-24 21:52 UTC
Labels: documentation
